### ISSUE TITLE
добавить картинку

### ISSUE THREAD

**Issue by pailik** [kubikvest/front#32]
над кнопкой НАЗВАНИЕ КВЕСТА добавить картинку 

размер картинки фиксированный ( ? ) 280х170
ширина кнопки фиксированная ( ? ) 280

нажать можно как на кнопку так и на каринку

![kartinka](https://cloud.githubusercontent.com/assets/20873407/21112090/708396d0-c0b5-11e6-92b6-b34eb16715c8.jpg)

**Comment by Edrick53** [comment]
Паха, добавь конкретные картинки квестов уже с иконками инфографики.
