### ISSUE TITLE
картинку на первый экран

### ISSUE THREAD

**Issue by pailik** [kubikvest/front#33]
на первый экран добавить картинку / лого / текст "Кубик уличный квест"
сделать кнопку после картинки и сделать ее больше

![kartinka_01_2](https://cloud.githubusercontent.com/assets/20873407/21145032/d0d7c936-c15d-11e6-9adc-ce089e4f3b90.jpg)

**Comment by Edrick53** [comment]
Картинку конкретную. Плюс тут надо оцентровать текста. И сделать чтобы кнопка truncate db была видна только с наших аккаунтов. При загрузке полоску почти не видно сделать ее толще заметнее.

**Comment by iMega** [comment]
Размер лого какой? Какая высота bg картины?
