### ISSUE TITLE
про текст (text-align)

### ISSUE THREAD

**Issue by pailik** [kubikvest/front#40]
Кнопки и заголовки текст по центру, остальной текст по левому краю

**Comment by iMega** [comment]
Текст у кнопок вроде по центру, можно точнее указать где не так?

**Comment by pailik** [comment]
Текст у кнопок по центру = норм
Текст у заголовков по центру на белом фоне (тикет #34)

имеется то что
первый экран один хедер (картинка, лого, название)
а игра другой хедер (название квеста на белом фоне)

текст “Для начала выбери квест!” (тикет #42)
