### ISSUE TITLE
картинки для первого экрана

### ISSUE THREAD

**Issue by pailik** [kubikvest/front#45]
![logo_0](https://cloud.githubusercontent.com/assets/20873407/21458421/492ca9ec-c947-11e6-9c0b-715e75646d67.png)
![heder_0](https://cloud.githubusercontent.com/assets/20873407/21458420/492036e4-c947-11e6-9182-e2ef31d99b84.png)

**Comment by pailik** [comment]
!!! картина не наша надо потом поставить другую !!! эту через призму получается мясо

**Comment by iMega** [comment]
Размер лого какой? Какая высота bg картины?

**Comment by iMega** [comment]
Нет потребности в тикете
